global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bosh-admin_server'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['server:8089'] # 对应 Gin 服务的端口